### ISSUE TITLE
Add filters

### ISSUE THREAD

**Issue by bohushvitali** [srid/devour-flake#18]
Add a filter to prevent pushing CUDA-enabled packages and devshells
Related:
- https://github.com/cachix/cachix/issues/377
- https://github.com/hercules-ci/hercules-ci-agent/issues/392

**Comment by srid** [comment]
Hmm, how is this related to this repo?

By the way, https://github.com/srid/nixci might be of interested if you are currently using devour-flake.

**Comment by srid** [comment]
Closing, per lack of response.
