### ISSUE TITLE
The option `nixpkgs.hostPlatform` is used but not defined.

### ISSUE THREAD

**Issue by locallycompact** [srid/devour-flake#25]
This happens when trying to use devour like in this job:

https://gitlab.horizon-haskell.net/web/docs.horizon-haskell.net/-/jobs/1418610

**Comment by srid** [comment]
See #23

```nix
let configForCurrentSystem = cfg: cfg.config.nixpkgs.hostPlatform.system == system;
```

Is this not how we check the system of a nixos configuration?

You can use `nixpkgs.hostPlatform = "x86_64-linux";` in your [studiopolis](https://gitlab.horizon-haskell.net/web/docs.horizon-haskell.net/-/blob/master/flake.nix?ref_type=heads) config to resolve this, but I'm wondering if my `configForCurrentSystem` should be rewritten.

**Comment by srid** [comment]
I suppose I should use `system`:

<img width="844" alt="image" src="https://github.com/srid/devour-flake/assets/3998/9c82b1f2-458a-453a-b9c0-316591b35caa">

**Comment by srid** [comment]
nixpkgs has a mess of system options:

<img width="928" alt="image" src="https://github.com/srid/devour-flake/assets/3998/a1255c8f-8330-4ed7-874c-772591cee615">

**Comment by srid** [comment]
cc @roberth - What system option should we use to answer the question "What platform this nixosconfiguration will build/run on?"

**Comment by srid** [comment]
@locallycompact Try this in the meanwhile: https://github.com/srid/devour-flake/pull/26

I believe `localSystem` should exist for all configurations, but not entirely sure.

**Comment by roberth** [comment]
Those options aren't suitable for reading, partly because of `nixpkgs.pkgs` and partly because of the legacy support.

Use `pkgs.stdenv.hostPlatform` or `pkgs.stdenv.hostPlatform.system` if you need it to be a string.

**Comment by roberth** [comment]
ie the module argument

**Comment by srid** [comment]
No modules are involved, because we are dealing a NixOS configuration built by `nixosSystem`. Okay, so it should be `cfg.pkgs.stdenv.hostPlatform.system`. Thanks!
