### ISSUE TITLE
bug: fails if there is no default package output

### ISSUE THREAD

**Issue by nrdxp** [srid/devour-flake#27]
```
error: flake 'path:/nix/store/p8vfkmfh43yy8lmz1r65dr9yq3ql7cd7-source' does not provide attribute 'packages.x86_64-linux.default', 'legacyPackages.x86_64-linux.default' or 'default'
Error: devour-flake failed to run (exited: 1)
```

~~see no reason why this should be a hard requirement, and didn't seem to be a problem in earlier versions.~~

The path listed in the error points to devour-flake itself, so the issue is a bit weirder than I first thought.

**Comment by srid** [comment]
Tim has confirmed that using `nixci` master this is not the issue, because that uses latest devour-flake.

I should release nixci 0.6.0, along with updated devour-flake, once https://github.com/srid/nixci/pull/63 is ready - then @shivaraj-bh can upstream it to nixpkgs.

**Comment by srid** [comment]
Closing as dup of https://github.com/srid/nixci/issues/64

**Comment by srid** [comment]
`nixci` 0.5.0 released to nixpkgs
